version: '3.8'

services:
  # nginx:
  #   depends_on:
  #     - node-app
  #     - client
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./Nginx
  #   ports:
  #     - "3050:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     
  node-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=4000
    depends_on:
      - mongo
      - redis
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - PORT=3000
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tunahan
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  mongo-data:
  redis-data:
